
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: store_data
    description: "Sales performance and related KPIs for stores"
    columns:
      - name: comp_status_desc
        description: ""
        data_type: text
      - name: comp_status_id
        description: ""
        data_type: text
      - name: conv_currency_desc
        description: ""
        data_type: text
      - name: conv_currency_id
        description: ""
        data_type: text
      - name: date
        description: ""
        data_type: date
      - name: fiscal_period_desc
        description: ""
        data_type: text
      - name: fiscal_period_id
        description: ""
        data_type: text
      - name: fiscal_week_desc
        description: ""
        data_type: text
      - name: fiscal_week_id
        description: ""
        data_type: text
      - name: fiscal_week_mmm_w
        description: ""
        data_type: text
      - name: fiscal_year_desc
        description: ""
        data_type: text
      - name: fiscal_year_id
        description: ""
        data_type: text
      - name: gender
        description: ""
        data_type: text
      - name: region_desc
        description: ""
        data_type: text
      - name: region_id
        description: ""
        data_type: text
      - name: retail_brand_site_desc
        description: ""
        data_type: text
      - name: retail_brand_site_id
        description: ""
        data_type: text
      - name: retail_district_desc
        description: ""
        data_type: text
      - name: retail_district_id
        description: ""
        data_type: text
      - name: row_count_lh1090_store_reporting
        description: ""
        data_type: integer
      - name: sales_org_desc
        description: ""
        data_type: text
      - name: sales_org_id
        description: ""
        data_type: text
      - name: site_id
        description: ""
        data_type: text
      - name: site_category_id
        description: ""
        data_type: text
      - name: site_format_desc
        description: ""
        data_type: text
      - name: site_key_id
        description: ""
        data_type: text
      - name: site_name_id
        description: ""
        data_type: text
      - name: site_number_id
        description: ""
        data_type: text
      - name: site_status_desc
        description: ""
        data_type: text
      - name: site_status_id
        description: ""
        data_type: text
      - name: site_type_desc
        description: ""
        data_type: text
      - name: site_type_id
        description: ""
        data_type: text
      - name: zone_id
        description: ""
        data_type: text
      - name: aur
        description: ""
        data_type: numeric
      - name: aur_lly
        description: ""
        data_type: numeric
      - name: aur_ly
        description: ""
        data_type: numeric
      - name: aur_ty_lly_percent
        description: ""
        data_type: numeric
      - name: aur_ty_lly_var
        description: ""
        data_type: numeric
      - name: aur_ty_ly_percent
        description: ""
        data_type: numeric
      - name: aur_ty_ly_var
        description: ""
        data_type: numeric
      - name: avt
        description: ""
        data_type: numeric
      - name: avt_lly
        description: ""
        data_type: numeric
      - name: avt_ly
        description: ""
        data_type: numeric
      - name: avt_ty_lly_percent
        description: ""
        data_type: numeric
      - name: avt_ty_lly_var
        description: ""
        data_type: numeric
      - name: avt_ty_ly_percent
        description: ""
        data_type: numeric
      - name: avt_ty_ly_var
        description: ""
        data_type: numeric
      - name: count_site_status_id
        description: ""
        data_type: text
      - name: eoh_str_qty
        description: ""
        data_type: text
      - name: gm_merch
        description: ""
        data_type: numeric
      - name: gm_percent_merch
        description: ""
        data_type: numeric
      - name: gm_percent_lly_merch
        description: ""
        data_type: numeric
      - name: gm_percent_ly_merch
        description: ""
        data_type: numeric
      - name: gm_bps_ty_lly_merch
        description: ""
        data_type: numeric
      - name: gm_bps_ty_ly_merch
        description: ""
        data_type: numeric
      - name: gm_lly_merch
        description: ""
        data_type: numeric
      - name: gm_ly_merch
        description: ""
        data_type: numeric
      - name: gm_ty_lly_percent_merch
        description: ""
        data_type: numeric
      - name: gm_ty_lly_var_merch
        description: ""
        data_type: numeric
      - name: gm_ty_ly_percent_merch
        description: ""
        data_type: numeric
      - name: gm_ty_ly_var_merch
        description: ""
        data_type: numeric
      - name: net_sls_amt
        description: ""
        data_type: numeric
      - name: net_sls_amt_lly
        description: ""
        data_type: numeric
      - name: net_sls_amt_ly
        description: ""
        data_type: numeric
      - name: net_sls_amt_ty_lly_percent
        description: ""
        data_type: numeric
      - name: net_sls_amt_ty_lly_var
        description: ""
        data_type: numeric
      - name: net_sls_amt_ty_ly_percent
        description: ""
        data_type: numeric
      - name: net_sls_amt_ty_ly_var
        description: ""
        data_type: numeric
      - name: net_sls_qty
        description: ""
        data_type: integer
      - name: net_sls_qty_lly
        description: ""
        data_type: integer
      - name: net_sls_qty_ly
        description: ""
        data_type: integer
      - name: net_sls_qty_ty_lly_percent
        description: ""
        data_type: numeric
      - name: net_sls_qty_ty_lly_var
        description: ""
        data_type: numeric
      - name: net_sls_qty_ty_ly_percent
        description: ""
        data_type: numeric
      - name: row_count_store_sales_gender
        description: ""
        data_type: integer
      - name: rtn_amt
        description: ""
        data_type: numeric
      - name: rtn_amt_percent
        description: ""
        data_type: numeric
      - name: rtn_amt_lly
        description: ""
        data_type: numeric
      - name: rtn_amt_ly
        description: ""
        data_type: numeric
      - name: rtn_amt_ty_ly_percent
        description: ""
        data_type: numeric
      - name: rtn_bps_ty_lly
        description: ""
        data_type: numeric
      - name: rtn_bps_ty_ly
        description: ""
        data_type: numeric
      - name: sls_trfc_amt_ty_lly_percent
        description: ""
        data_type: numeric
      - name: sls_trfc_amt_ty_ly_percent
        description: ""
        data_type: numeric
      - name: sls_trfc_gm_ty_lly_percent_merch
        description: ""
        data_type: numeric
      - name: sls_trfc_gm_ty_ly_percent_merch
        description: ""
        data_type: numeric
      - name: str_pln_sls_amt
        description: ""
        data_type: numeric
      - name: traffic_in
        description: ""
        data_type: integer
      - name: traffic_in_lly
        description: ""
        data_type: integer
      - name: traffic_in_ly
        description: ""
        data_type: integer
      - name: traffic_in_ttl_conv_percent
        description: ""
        data_type: numeric
      - name: traffic_in_ttl_conv_percent_lly
        description: ""
        data_type: numeric
      - name: traffic_in_ttl_conv_percent_ly
        description: ""
        data_type: numeric
      - name: traffic_in_ttl_conv_percent_ty_lly_var
        description: ""
        data_type: numeric
      - name: traffic_in_ttl_conv_percent_ty_ly_var
        description: ""
        data_type: numeric
      - name: traffic_in_ty_lly_percent
        description: ""
        data_type: numeric
      - name: traffic_in_ty_lly_var
        description: ""
        data_type: numeric
      - name: traffic_in_ty_ly_percent
        description: ""
        data_type: numeric
      - name: traffic_in_ty_ly_var
        description: ""
        data_type: numeric
      - name: upt
        description: ""
        data_type: numeric
      - name: upt_lly
        description: ""
        data_type: numeric
      - name: upt_ly
        description: ""
        data_type: numeric
      - name: upt_ty_lly_percent
        description: ""
        data_type: numeric
      - name: upt_ty_lly_var
        description: ""
        data_type: numeric
      - name: upt_ty_ly_percent
        description: ""
        data_type: numeric
      - name: upt_ty_ly_var
        description: ""
        data_type: numeric

 
  - name: Store_Flash

    columns:

      # -------------------
      # DIMENSIONS
      # -------------------
      - name: date
        description: "Transaction date"
        type: date

      - name: dist_channel
        description: "Distribution channel"
        type: string

      - name: loc_comp_status
        description: "Location competition status"
        type: string

      - name: loc_cannibalization_flag
        description: "Location cannibalization flag"
        type: string

      - name: market
        description: "Market name"
        type: string

      - name: store_number
        description: "Store number"
        type: number

      - name: store_division
        description: "Store division"
        type: string

      - name: store_name
        description: "Store name"
        type: string


metrics:
  # ============================
  # ====== AOV Metrics =========
  # ============================
  - name: avg_merch_dmd_aov_mtd
    label: "Average AOV MTD"    
    type: average
    type_params:
      measure: merch_dmd_aov_mtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: avg_merch_dmd_aov_qtd
    label: "Average AOV QTD"    
    type: average
    type_params:
      measure: merch_dmd_aov_qtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: avg_merch_dmd_aov_wtd
    label: "Average AOV WTD"    
    type: average
    type_params:
      measure: merch_dmd_aov_wtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: avg_merch_dmd_aov_ytd
    label: "Average AOV YTD"    
    type: average
    type_params:
      measure: merch_dmd_aov_ytd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: merch_dmd_aov_ty_ly_pct
    label: "AOV % Change TY vs LY"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  # ============================
  # ====== UPT Metrics =========
  # ============================
  - name: avg_merch_dmd_upt_mtd
    label: "Average UPT MTD"    
    type: average
    type_params:
      measure: merch_dmd_upt_mtd

    meta:
      numberStyle:
        format: "0.00"

  - name: avg_merch_dmd_upt_qtd
    label: "Average UPT QTD"    
    type: average
    type_params:
      measure: merch_dmd_upt_qtd

    meta:
      numberStyle:
        format: "0.00"

  - name: avg_merch_dmd_upt_wtd
    label: "Average UPT WTD"    
    type: average
    type_params:
      measure: merch_dmd_upt_wtd

    meta:
      numberStyle:
        format: "0.00"

  - name: avg_merch_dmd_upt_ytd
    label: "Average UPT YTD"    
    type: average
    type_params:
      measure: merch_dmd_upt_ytd

    meta:
      numberStyle:
        format: "0.00"

  - name: merch_dmd_upt_ty_ly_pct
    label: "UPT % Change TY vs LY"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  # ===================================
  # === Net Merchandise Demand =======
  # ===================================
  - name: total_net_merch_dmd_mtd
    label: "Total Net Merch Demand MTD"    
    type: sum
    type_params:
      measure: net_merch_dmd_mtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: total_net_merch_dmd_qtd
    label: "Total Net Merch Demand QTD"    
    type: sum
    type_params:
      measure: net_merch_dmd_qtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: total_net_merch_dmd_wtd
    label: "Total Net Merch Demand WTD"    
    type: sum
    type_params:
      measure: net_merch_dmd_wtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: total_net_merch_dmd_ytd
    label: "Total Net Merch Demand YTD"    
    type: sum
    type_params:
      measure: net_merch_dmd_ytd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: net_merch_dmd_ty_ly_pct
    label: "% Change Net Merch Demand TY vs LY"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  - name: net_merch_dmd_vs_site_net_sls_fcst_amt_pct
    label: "Net Merch Demand vs Site Sales Forecast %"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  # ===================================
  # === Site Net Sales Forecast =======
  # ===================================
  - name: total_site_net_sls_fcst_amt_mtd
    label: "Total Site Net Sales Forecast MTD"    
    type: sum
    type_params:
      measure: site_net_sls_fcst_amt_mtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: total_site_net_sls_fcst_amt_qtd
    label: "Total Site Net Sales Forecast QTD"    
    type: sum
    type_params:
      measure: site_net_sls_fcst_amt_qtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: total_site_net_sls_fcst_amt_wtd
    label: "Total Site Net Sales Forecast WTD"    
    type: sum
    type_params:
      measure: site_net_sls_fcst_amt_wtd

    meta:
      numberStyle:
        format: "$#,##0.00"

  - name: total_site_net_sls_fcst_amt_ytd
    label: "Total Site Net Sales Forecast YTD"    
    type: sum
    type_params:
      measure: site_net_sls_fcst_amt_ytd

    meta:
      numberStyle:
        format: "$#,##0.00"

  # ============================
  # ====== Traffic KPIs ========
  # ============================
  - name: avg_traffic_in_conv_pct_mtd
    label: "Traffic In Conversion % MTD"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  - name: avg_traffic_in_conv_pct_qtd
    label: "Traffic In Conversion % QTD"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  - name: avg_traffic_in_conv_pct_wtd
    label: "Traffic In Conversion % WTD"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  - name: avg_traffic_in_conv_pct_ytd
    label: "Traffic In Conversion % YTD"    
    type: number

    meta:
      numberStyle:
        format: "0.00%"

  - name: total_traffic_in_qty_mtd
    label: "Total Traffic In Qty MTD"    
    type: sum
    type_params:
      measure: traffic_in_qty_mtd

    meta:
      numberStyle:
        format: "#,##0"

  - name: total_traffic_in_qty_qtd
    label: "Total Traffic In Qty QTD"    
    type: sum
    type_params:
      measure: traffic_in_qty_qtd

    meta:
      numberStyle:
        format: "#,##0"

  - name: total_traffic_in_qty_wtd
    label: "Total Traffic In Qty WTD"    
    type: sum
    type_params:
      measure: traffic_in_qty_wtd

    meta:
      numberStyle:
        format: "#,##0"

  - name: total_traffic_in_qty_ytd
    label: "Total Traffic In Qty YTD"    
    type: sum
    type_params:
      measure: traffic_in_qty_ytd

    meta:
      numberStyle:
        format: "#,##0"
